# Generated by Django 5.2.1 on 2025-06-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appParser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configrec',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='configrec',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='configrec',
            old_name='updated_at',
            new_name='expiryDate',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='filename',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='filename',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='filename',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='frequency',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='frequency',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='frequency',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='locationtype',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='locationtype',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='locationtype',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='parser',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='parser',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='parser',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AddField(
            model_name='configrec',
            name='destination',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='destination_location', to='appParser.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configrec',
            name='fileName',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appParser.filename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configrec',
            name='frequency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appParser.frequency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configrec',
            name='source',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appParser.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configrec',
            name='contractName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appParser.contract'),
        ),
    ]
