# Generated by Django 5.2.1 on 2025-06-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appParser', '0003_rename_contractname_contract_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filename',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='parser',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='parser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='configlog',
            name='parser',
        ),
        migrations.RenameField(
            model_name='configlog',
            old_name='logId',
            new_name='sourceFile',
        ),
        migrations.AddField(
            model_name='configlog',
            name='contractID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appParser.contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configlog',
            name='frequency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appParser.frequency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configlog',
            name='sourceLogID',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='configlog',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appParser.status'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConfigRec',
        ),
        migrations.DeleteModel(
            name='FileName',
        ),
        migrations.DeleteModel(
            name='Parser',
        ),
    ]
