# Generated by Django 5.2.1 on 2025-06-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appParser', '0004_remove_filename_createdby_remove_parser_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='frequency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appParser.frequency'),
        ),
    ]
