# Generated by Django 5.2.1 on 2025-06-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appParser', '0005_alter_contract_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='fullName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='outputObjectName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='outputSchemaName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='preProcessor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sourceFileNamingConvention',
            field=models.CharField(max_length=200),
        ),
    ]
