# Generated by Django 5.2.1 on 2025-06-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appParser', '0006_alter_contract_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configlog',
            old_name='createdAt',
            new_name='dateExecuted',
        ),
        migrations.RemoveField(
            model_name='configlog',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='configlog',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='configlog',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='configlog',
            name='updatedAt',
        ),
    ]
