# Generated by Django 5.2.1 on 2025-06-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appParser', '0007_rename_createdat_configlog_dateexecuted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configlog',
            name='contractID',
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=200)),
                ('sourceFileLocation', models.CharField(max_length=200)),
                ('sourceFileNamingConvention', models.CharField(max_length=200)),
                ('outputSchemaName', models.CharField(max_length=200)),
                ('outputObjectName', models.CharField(max_length=200)),
                ('parser', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frequency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appParser.frequency')),
            ],
        ),
        migrations.AddField(
            model_name='configlog',
            name='fileType',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appParser.config'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
